### ISSUE TITLE
Outbound Call Issue

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-web-phone#98] opened 2016-12-05 16:19 UTC
Hello There

I am trying to make outbound call and following is my code:

```js
 acRCWebRTC.session = rc_webPhone.userAgent.invite(To_Number, {
        media: {
            render: {
                remote: document.getElementById("remoteVideo"),
                local: document.getElementById("localVideo")
            }
        }
    });
    onAccepted(acRCWebRTC.session);
```

and following is error:

```
Mon Dec 05 2016 21:22:26 GMT+0530 (IST) | sip.parser | error parsing header "From"

Dec 05 2016 21:22:14 GMT+0530 (IST) | sip.parser | error parsing header "From"
LoggerFactory.print @ sip-0.7.5.js:2884
LoggerFactory.(anonymous function) @ sip-0.7.5.js:2901
Logger.(anonymous function) @ sip-0.7.5.js:2895
Parser.parseMessage @ sip-0.7.5.js:3315
onMessage @ sip-0.7.5.js:8493
ws.onmessage @ sip-0.7.5.js:8375
js-all-min-4.js?_=sandbox.1:formatted:36638 WebRTC Event: ICE: iceCandidate
sip-0.7.5.js:2884 Mon Dec 05 2016 21:22:18 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 400 Bad Request
Via: SIP/2.0/WSS rllb1kb8gf96.invalid;rport=16610;received=10.28.20.10;branch=z9hG4bK3243543
From: <sip:@sip.devtest.ringcentral.com>;tag=6d9mmrcc6m
To: <sip:+12014845435@sip.devtest.ringcentral.com>
Error-Info: <sip:+12014845435@sip.devtest.ringcentral.com>;cause="[line 008] SIP syntax error"
Content-Length: 0
```

any help is appreciated,

thanks in advance,

**Comment by vyshakhbabji** [comment] 2016-12-05 19:05
Hi @srigottipati , 

I am unable to reproduce this issue. 
Can you send us a sip log for a complete session to devsupport@ringcentral.com along with your organization details  for further investigation?

**Comment by srigottipati** [comment] 2016-12-06 01:35
hi @vyshakhbabji ,

thanks for the reply and suggestion.
can you provide steps to retrieve sip log for a complete session?

thanks
sri

**Comment by vyshakhbabji** [comment] 2016-12-07 19:01
The **from** number is not passed in the invite .  Please fix that . I am closing the issue. 

From: <sip:+**1XXXXXXXXX**@sip.devtest.ringcentral.com>

**Comment by srigottipati** [comment] 2016-12-12 12:39
hi vyshakhbabi,

thanks for the reply,

i am still getting the issue and following is the error

SIP/2.0 404 Not Found
Via: SIP/2.0/WSS 9cblg6ud7p4q.invalid;rport=11681;received=10.28.16.10;branch=z9hG4bK3765716
From: <sip:12673173073*101@sip.devtest.ringcentral.com>;tag=mmual33fpg
To: <sip:+12014845435@sip.devtest.ringcentral.com>;tag=gK0cb51efe
Call-ID: pna8ks555sakv1s94vc3
CSeq: 5023 INVITE
User-Agent: RC_SIPWRP_20.81
Content-Length: 0

thanks,

sri

**Comment by vyshakhbabji** [comment] 2017-01-16 19:11
Handling this case via support ticket (devsupport@ringcentral.com)

**Comment by kirill-konshin** [comment] 2017-08-22 17:23
Closing due to inactivity.

**Closed by kirill-konshin** 2017-08-22 17:23 UTC
