### ISSUE TITLE
sip.parser | error parsing header "From"

### ISSUE THREAD

**Issue by MathikumarC** [ringcentral/ringcentral-web-phone#104] opened 2017-01-04 05:00 UTC
Dear Team,

Sometimes we are getting below error message when we make outgoing call. It is not reproducible all the times. We are using below invite to make call. 

```javascript
webPhone.userAgent.invite(number, {
       media: {
           render: {
               remote: document.getElementById('remoteVideo'),
               local: document.getElementById('localVideo')
           }
       }  
```

Below are the short SIP logs for analysis. As marked in bold italics ,from number is sent  (company default number) to SIP server. But we are getting Bad Request contains empty from number. 

Please look into this.

```
Wed Jan 04 2017 10:12:13 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/WSS 50dl3074qq8t.invalid;branch=z9hG4bK9304771;rport=4231;received=10.13.120.10
To: <sip:+**91XXXXXXXXXX**@sip.ringcentral.com>
From: <sip:**XXXXXXXXXX*XXX**@sip.ringcentral.com>;tag=60kshalnju
Call-ID: u9leg4q6n0u6kgk80jlg
CSeq: 5970 INVITE
Server: kamailio (4.1.5 (x86_64/linux))
Content-Length: 0



sip-0.7.5.min.js:36 Wed Jan 04 2017 10:12:13 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 400 Bad Request
Via: SIP/2.0/WSS 50dl3074qq8t.invalid;rport=4231;received=10.13.120.10;branch=z9hG4bK9304771
**From: <sip:@sip.ringcentral.com**>;tag=60kshalnju
To: <sip:+91XXXXXXXXXX@sip.ringcentral.com>
Error-Info: <sip:+91XXXXXXXXXX@sip.ringcentral.com>;cause="[line 008] SIP syntax error"
Content-Length: 0



sip-0.7.5.min.js:36 Wed Jan 04 2017 10:12:13 GMT+0530 (IST) | sip.sipmessage | error parsing "From" header field with value "<sip:@sip.ringcentral.com>;tag=60kshalnju"
c.print @ sip-0.7.5.min.js:36
c.(anonymous function) @ sip-0.7.5.min.js:36
b.(anonymous function) @ sip-0.7.5.min.js:36
parseHeader @ sip-0.7.5.min.js:37
c @ sip-0.7.5.min.js:36
d.parseMessage @ sip-0.7.5.min.js:37
onMessage @ sip-0.7.5.min.js:39
ws.onmessage @ sip-0.7.5.min.js:39
sip-0.7.5.min.js:36 Wed Jan 04 2017 10:12:13 GMT+0530 (IST) | sip.parser | error parsing header "From"
c.print @ sip-0.7.5.min.js:36
c.(anonymous function) @ sip-0.7.5.min.js:36
b.(anonymous function) @ sip-0.7.5.min.js:36
d.parseMessage @ sip-0.7.5.min.js:37
onMessage @ sip-0.7.5.min.js:39
ws.onmessage @ sip-0.7.5.min.js:39
sip-0.7.5.min.js:36 Wed Jan 04 2017 10:12:13 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 400 Bad Request
Via: SIP/2.0/WSS 50dl3074qq8t.invalid;rport=4231;received=10.13.120.10;branch=z9hG4bK9304771
From: <sip:@sip.ringcentral.com>;tag=60kshalnju
To: <sip:+91XXXXXXXXXX@sip.ringcentral.com>
Error-Info: <sip:+91XXXXXXXXX@sip.ringcentral.com>;cause="[line 008] SIP syntax error"
Content-Length: 0
```

We will send you the detailed SIP logs to devsupport@ringcentral.com

Thanks
Mathikumar

**Comment by vyshakhbabji** [comment] 2017-01-10 19:50
Hi Mathi,

I couldn't reproduce this issue by testing. How often do you see the issue?  I also see that the phone number hasn't been passed at all.  

For example   ==>  From: sip:@sip.ringcentral.com;tag=60kshalnju  . 

Can you make sure, while passing the number parameter you use E164 format of the phone number? Let us know what the results are.

**Comment by MathikumarC** [comment] 2017-01-11 05:24
Vyshakh , 

Thanks for your reply.

From below logs,while requesting SIP server, we are sending FROM number.(Marked as bold)

SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/WSS 50dl3074qq8t.invalid;branch=z9hG4bK9304771;rport=4231;received=10.13.120.10
To: sip:+**91XXXXXXXXXX**@sip.ringcentral.com
From: sip:XXXXXXXXXX*XXX@sip.ringcentral.com;tag=60kshalnju

But we are getting 400 Bad request stating that

sip.sipmessage | error parsing "From" header field with value "sip:@sip.ringcentral.com;tag=60kshalnju"

And the FROM number is same for the all the calls(default number). Only for few calls
 (we can say 3-5% ) we are getting above error.

Please clarify if i am wrong.

Thanks
Mathikumar.C

**Comment by vyshakhbabji** [comment] 2017-03-16 23:29
Issue not reproducible while tested on US IP addresses. Tracking the issue internally.  Current issue resolved. Closing this case.

**Closed by vyshakhbabji** 2017-03-16 23:29 UTC
